name: Send Branch to QA
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
jobs:
  send-branch-to-qa:
    if: ${{ startsWith(github.event.comment.body, '/deploy qa') && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Determine Deployment branch
        id: deploy-branch
        run: |
          COMMENT="${{github.event.comment.body}}"
          COMMENT_BRANCH=$(echo $COMMENT | sed -r "s/.*\/deploy (qa[-0-9a-zA-Z]+).*/\1/" | awk '{print tolower($0)}')

          if [[ $COMMENT_BRANCH == qa* ]]; then
            echo "NAME=$COMMENT_BRANCH" >> $GITHUB_OUTPUT
          else
            echo "NAME=''" >> $GITHUB_OUTPUT
          fi
      - uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.deploy-branch.outputs.NAME != '' }}
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: "+1"
      - uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.deploy-branch.outputs.NAME == '' }}
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: "-1"
      - name: Push to QA Branch
        if: ${{ steps.deploy-branch.outputs.NAME != '' }}
        id: push-current-branch-to-qa-branch
        run: |
          CURRENT_BRANCH=$(git branch --show-current)
          QA_BRANCH="${{ steps.deploy-branch.outputs.NAME }}"

          if [[ "$QA_BRANCH" == "master" ]]; then
            echo "can't force push to master"
            exit 1
          fi

          if [[ "$QA_BRANCH" == "main" ]]; then
            echo "can't force push to main"
            exit 1
          fi

          echo "PR NUMBER: ${{ github.event.pull_request.number }}"
          echo "PR ${{ github.event.issue.pull_request }}"
          echo "PR number ${{ github.event.issue.pull_request.number }}"
          echo "PR id ${{ github.event.issue.pull_request.id }}"

          echo "pushing $CURRENT_BRANCH to $QA_BRANCH"

          git push --force origin "$CURRENT_BRANCH":"$QA_BRANCH"
      - uses: peter-evans/create-or-update-comment@v2
        if: success()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "Pushed to this branch successfully to ${{ steps.deploy-branch.outputs.NAME }}. Check CI for further build info"
      - uses: peter-evans/create-or-update-comment@v2
        if: failure()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "Could not push this branch to ${{ steps.deploy-branch.outputs.NAME }}. Check the Github Actions Workflow Logs for more details"
