name: Send Branch to QA
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
jobs:
  send-branch-to-qa:
    if: startsWith(github.event.comment.body, '/deploy qa') && github.event.issue.pull_request
    runs-on: ubuntu-22.04
    env:
      PR_NUMBER: ${{github.event.issue.number}}
      WORKFLOW_LINK: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      GH_TOKEN: ${{ github.token }}
      CI_LINK: "https://app.circleci.com/pipelines/github/${{ github.repository }}"
    steps:
      - uses: actions/checkout@v3
      - name: Determine Deployment branch
        id: determine-deployment-branch
        run: |
          COMMENT="${{github.event.comment.body}}"
          COMMENT_BRANCH=$(echo $COMMENT | sed -r "s/.*\/deploy (qa[-0-9a-zA-Z]+).*/\1/" | awk '{print tolower($0)}')

          if [[ $COMMENT_BRANCH == qa* ]]; then
            echo "DETERMINED COMMENT BRANCH!: $COMMENT_BRANCH"
            echo "NAME=$COMMENT_BRANCH" >> $GITHUB_OUTPUT
          else
            echo "COULD NOT DETERMINE COMMENT BRANCH!: $COMMENT_BRANCH"
            echo "NAME=" >> $GITHUB_OUTPUT
          fi
      - name: Unable to Determine Determine Branch
        id: unable-to-determine-deployment-branch-comment
        if: steps.determine-deployment-branch.outputs.NAME == ''
        run: |
            BODY="Unable to determine branch to deploy. Check the [Workflow log]($WORKFLOW_LINK) for more details"

            gh issue comment $PR_NUMBER --body "$BODY"
      - uses: actions/github-script@v6
        if: steps.determine-deployment-branch.outputs.NAME == ''
        with:
          script: |
            try {
              await github.rest.reactions.createForIssueComment({
                ...context.repo,
                comment_id: context.payload.comment.id,
                content: '-1',
              });
            }
            catch (err) {
              core.setFailed(`Request failed with error ${err}`);
            }
      - uses: actions/github-script@v6
        if: steps.determine-deployment-branch.outputs.NAME != ''
        with:
          script: |
            try {
              await github.rest.reactions.createForIssueComment({
                ...context.repo,
                comment_id: context.payload.comment.id,
                content: '+1',
              });
            }
            catch (err) {
              core.setFailed(`Request failed with error ${err}`);
            }
      - name: Push to QA Branch
        if: steps.determine-deployment-branch.outputs.NAME != ''
        id: push-current-branch-to-qa-branch
        run: |
          gh pr checkout $PR_NUMBER

          CURRENT_BRANCH=$(git branch --show-current)
          DEPLOYMENT_BRANCH="${{ steps.determine-deployment-branch.outputs.NAME }}"

          if [[ "$DEPLOYMENT_BRANCH" == "master" ]]; then
            echo "can't force push to master"
            exit 1
          fi

          if [[ "$DEPLOYMENT_BRANCH" == "main" ]]; then
            echo "can't force push to main"
            exit 1
          fi
          echo "pushing $CURRENT_BRANCH to $DEPLOYMENT_BRANCH"

          git push --force origin "$CURRENT_BRANCH":"$DEPLOYMENT_BRANCH"
      - name: debugging
        run: |
          echo "push-current-branch-to-qa-branch outcome: ${{steps.push-current-branch-to-qa-branch.outcome}}"
          echo "SUCCESS?: ${{steps.push-current-branch-to-qa-branch.outcome == 'success'}}"
          echo "FAILURE?: ${{steps.push-current-branch-to-qa-branch.outcome == 'failure'}}"
      - name: Create Successful Comment
        if: ${{ steps.push-current-branch-to-qa-branch.outcome == 'success' }}
        env:
          BRANCH: ${{ steps.determine-deployment-branch.outputs.NAME }}
        run: |
            CI_LINK="${CI_LINK}?branch=${BRANCH}"
            BODY="I have pushed this branch successfully to $BRANCH. Check [CI build logs]($CI_LINK) for more details"

            gh issue comment $PR_NUMBER --body "$BODY"
      - name: Add Failure Comment
        if: ${{ steps.push-current-branch-to-qa-branch.outcome == 'failure' }}
        env:
          BRANCH: ${{ steps.determine-deployment-branch.outputs.NAME }}
        run: |
            BODY="I could not push this branch to $BRANCH. Check the [Workflow log]($WORKFLOW_LINK) for more details"

            gh issue comment $PR_NUMBER --body "$BODY"
