name: Send Branch to QA
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
jobs:
  send-branch-to-qa:
    if: ${{ startsWith(github.event.comment.body, '/deploy qa') && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Determine Deployment branch
        id: determine-deployment-branch
        run: |
          COMMENT="${{github.event.comment.body}}"
          COMMENT_BRANCH=$(echo $COMMENT | sed -r "s/.*\/deploy (qa[-0-9a-zA-Z]+).*/\1/" | awk '{print tolower($0)}')

          if [[ $COMMENT_BRANCH == qa* ]]; then
            echo "NAME=$COMMENT_BRANCH" >> $GITHUB_OUTPUT
          else
            echo "NAME=''" >> $GITHUB_OUTPUT
          fi
      - uses: actions/github-script@v4
        if: ${{ steps.determine-deployment-branch.outputs.NAME != '' }}
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });
      - name: DEBUG
        run: |
            echo "event.issue.html_url: ${{github.event.issue.html_url}}"
            echo "event.issue.number: ${{github.event.issue.number}}"
            echo "event.issue.id: ${{github.event.issue.id}}"
            echo "event.issue.pull_request: ${{github.event.issue.pull_request}}""
            echo "event.issue.pull_request.id: ${{github.event.issue.pull_request.id}}""
            echo "event.issue.pull_request.number: ${{github.event.issue.pull_request.number}}""

            #gh issue comment $ISSUE --body "Thank you for opening this issue!"
            #I could not push this branch to ${{ steps.determine-deployment-branch.outputs.NAME }}. Check the Github Actions Workflow logs for more details

      - name: Push to QA Branch
        if: ${{ steps.determine-deployment-branch.outputs.NAME != '' }}
        id: push-current-branch-to-qa-branch
        run: |
          gh pr checkout ${{github.event.issue.number}}

          CURRENT_BRANCH=$(git branch --show-current)
          QA_BRANCH="${{ steps.determine-deployment-branch.outputs.NAME }}"

          if [[ "$QA_BRANCH" == "master" ]]; then
            echo "can't force push to master"
            exit 1
          fi

          if [[ "$QA_BRANCH" == "main" ]]; then
            echo "can't force push to main"
            exit 1
          fi

          echo "pushing $CURRENT_BRANCH to $QA_BRANCH"

          git push --force origin "$CURRENT_BRANCH":"$QA_BRANCH"
      - name: Successful Comment
        if: success()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            I have pushed this branch successfully to ${{ steps.determine-deployment-branch.outputs.NAME }}. Check CI build logs for more details
      - name: Failure Comment
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            I could not push this branch to ${{ steps.determine-deployment-branch.outputs.NAME }}. Check the Github Actions Workflow logs for more details
